Config = {}
Config.FortuneCookie = {
    "Kdo se bojí smrti, už přišel o život.",
    "Po každém vítězství si utáhni helmu.",
    "Ti, kteří přemýšlejí o nepohodlí povinnosti jsou zbabělci.",
    "Ani nejlepší sokol ničeho neuloví, když se mu nedovolí vzlétnout.",
    "Kočka, která často mňouká, chytí málo myší.",
    "Jenom blbec neláme větve stromu kaki.",
    "Jen blázen nevyleze na horu fuji nikdy, a nebo dvakrát.",
    "Noboraru baka nido noboru baka.",
    "Vědomosti jsou poklad, který svého majitele všude provází.",
    "Vosa bodne do uplakané tváře.",
    "Neptej se na věk, ptej se na zkušenosti.",
    "Bohatí nejsou milosrdní, a milosrdní nejsou bohatí.",
    "Milované dítě vyprav do světa na zkušenou.",
    "Muž se má podobat borovici, žena vistárii.",
    "Hráz protrhnou mravenčí chodbičky.",
    "Slibuj pomalu, ale sliby plň hned.",
    "Děti nás vážou ke třem světům: minulosti, přítomnosti a budoucnosti.",
    "Štěstí se nečekaně samo oznámí.",
    "Jen ti, kdož nezapomenou předchozích zkušeností, se stanou mistry.",
    "Lidský život je jako svíčka ve větru.",
    "S prvním pohárem člověk pije víno - při druhém víno pije víno - při třetím víno pije člověka.",
    "Dokonce i malý brouček má svou malinkou dušičku.",
    "Zlé skutky se vracejí zpět k tomu, kdo je spáchal.",
    "Kdo pije, ví, jak víno škodí, kdo nepije, neví, jak prospívá.",
    "Náhodou zívne pes - a moucha vlítne psovi do tlamy.",
    "Kdo dobře zná sám sebe, nebojí se jiných.",
    "Závazek vůči rodičům je vyšší než hory a hlubší než moře.",
    "Skutečné mistrovství vypadá jednoduše.",
    "S člověkem, o kterém pochybuješ, nespolupracuj, o člověku, se kterým spolupracuješ, nepochybuj!",
    "Věštec sám nezná svůj vlastní osud.",
    "Mám-li být bit, pak rodičovskou holí.",
    "Ke mletí potřebuješ kámen, k vydělávání peněz trpělivost.",
    "Lež se stane pravdou jen tehdy, když jí člověk chce věřit.",
    "Ke starému člověku se chovej jako ke svému otci.",
    "Člověka si pamatují lidé jednu generaci, ale jeho skutky navěky.",
    "Ženu si vybírej v kuchyni.",
    "Ženy a rýže nebudeš mít nikdy dost.",
    "Povaha tříletého zůstává do sta.",
    "Ráno jíme, abychom vydrželi peklo pracovního dne, večer jíme, abychom se radovali.",
    "Chudoba je počátek světového bohatství.",
    "Básníci znají i krajiny, kde nikdy nebyli.",
    "Hlavní město je to, v němž žiješ.",
    "Kdo neuměl žít, nebude umět umírat.",
    "Kov se pozná v ohni, člověk při víně.",
    "Kráva pije vodu a je z ní mléko, zmije pije vodu a je z ní jed.",
    "Mnozí přátelé se nehodí ani k pití čaje.",
    "Nahatí nic neztratí.",
    "Věř jenom polovině toho, co slyšíš!",
    "Špatná manželka jako neúrodné pole - na dlouhých šedesát let.",
    "Zařízne-li chudý k obědu slepici, je nemocný on, nebo ta slípka.",
    "Velké pohromy vznikají z malých příčin.",
    "Víno je lepší než sto lékařů, ale je i příčinou sta chorob.",
    "Zbytečná věc - zbytečná starost.",
    "Ani nejdražší zrcadlo nezrcadlí rub.",
    "Jednou sám vidět je lepší než stokrát slyšet.",
    "Štěstí rádo navštěvuje dům, ve kterém vládne dobrá vůle.",
    "Peníze si zamykej, ženu ne!",
    "Nikdo z nás není tak chytrý jako my všichni dohromady.",
    "Kdo se směje, místo aby zuřil, je vždycky silnější.",
    "Hádka je jako přeháňka, nikdy nevíš, kdy se spustí.",
    "I v pokoji o tisíci rohožích potřebuješ k přespání jen jednu rohož.",
    "Štěstí přichází tam,kde nechybí smích.",
    "Co bys rád řekl dnes, řekni raději zítra.",
    "Přehnaná zdvořilost se stává urážkou.",
    "Žena a rohože jsou lepší nové.",
    "Úhledně psát umí mnozí, ale čtivě málokdo.",
    "Když bojují dva tygři je jeden odsouzen k zranění a druhý k smrti.",
    "Neptej se na věk, ptej se na zkušenosti.",
    "Lidé jsou všude stejní, jen zvyky se liší jeden od druhého.",
    "Draze koupené levnější darovaného.",
    "Zeptáš-li se, stydíš se za svou nevědomost teď, nezeptáš-li se, stydíš se celý život.",
    "Husy chodí v hejnech,orel létá sám.",
    "Žena je ústřední sloup domu.",
    "Lezeš-li vysoko, začni lézt odzdola.",
    "Prostořekost, toť pramen mnoha neshod.",
    "Na plody své práce čekej trpělivě, můžeš si i zdřímnout.",
    "Ví to celé město, jenom manžel ne.",
    "I mezi přáteli má vládnout zdvořilost.",
    "Květina je krásná polorozkvetlá, opilost také.",
    "Letní oblohou a lidským srdcem se nikdy nemůžeš být jist.",
    "Sto dní práce, jeden den radosti.",
    "Trpělivost je nejdůležitější vlastnost.",
    "Výchova znamená více než původ.",
    "Meditovat nad svou příští dráhou - dobře bavit myši pod podlahou.",
    "Vstoupíš-li do vesnice, řiď se jejími zákony.",
    "Když se tě ptají, neprozradíš nic, ale sám od sebe řekneš vše.",
    "V trpělivosti a harmonii je skutečná síla.",
    "Dlouhý život - mnoho ostud.",
    "Lidský život je stejně křehký jako květina, která kvete jen chvíli.",
    "Až když máš děti, začneš ctít své rodiče.",
    "Tvá silná stránka bývá počátkem tvé zkázy.",
    "I tisícimílová cesta začíná prvním krokem.",
    "Víno je králem léků.",
    "Pivo je králem léků.",
    "Učení je jako tlačení vozu do kopce - trochu povolíš a hned jede zpátky.",
    "Přátelé jsou jako nasolené slívy; čím starší, tím lepší.",
    "Jez do polosyta, pij do polopita.",
    "Ani veškerá temnota světa nedokáže uhasit světlo jediné svíčky.",
    "Co děláš s radostí, to tě neunaví.",
    "Člověk denně opravuje své vlasy. Proč ne také své srdce?",
    "Daruješ-li člověku rybu, nakrmíš ho na jeden den, naučíš-li ho lovit, dáš mu potravu pro celý život.",
    "Dejte pozor na to, co není.",
    "Dobré zprávy se z domu nedostanou – špatné se roznesou na tisíc mil.",
    "Dokud neodejdou špatní, dobří nemají kudy vstoupit.",
    "Chceš-li být šťasten jeden den, opij se. Chceš-li být šťasten jeden rok, ožeň se. Chceš-li být šťasten celý život, založ si zahradu.",
    "Jeden obraz vydá za tisíc slov.",
    "Jedním klíčem otevřeš jen jeden zámek.",
    "Jen cizíma očima lze vidět své nedostatky.",
    "Jestli můžete člověka naučiti dobrému a nečiníte toho – ztrácíte bratra.",
    "Kdo vidí stromy ve vodě, vidí ryby na stromech.",
    "Kdysi jsme byli jako rybky v jedné vodě – dnes už jsme ptáci, každý na jiné větvi.",
    "Koně prověří dlouhá cesta.",
    "Láska obměkčí i to nejtvrdší srdce.",
    "Lépe děti vychovávat, než pro ně hromadit majetek.",
    "Lepší být živým žebrákem, než mrtvým panovníkem.",
    "Neexistují žádné cesty; je třeba je vyšlapat.",
    "Nemáme nikdy tak potřebí svého důvtipu, jako když jednáme s hlupákem.",
    "Není to víno, co činí člověka opilým – je to on sám.",
    "Neuznáš-li svou chybu, děláš další chybu.",
    "Omyly moudrého člověka se podobají zatmění slunce. Když se mýlí, všichni to vidí, a vidí také, jak se napravuje.",
    "Papoušek umí mluvit, přesto patří do čeledi ptáků.",
    "Pěstovat vědu a nemilovat lidi je jako rozžehnout pochodeň a zavřít oči.",
    "Porážka je matkou úspěchu.",
    "Představený správy smí i požáry zakládat, avšak lidu není dovoleno ani zapálit svíčku.",
    "Slova jsou hlasem srdce.",
    "Slova jsou prázdná, ale štětec na psaní zanechává stopy.",
    "Sto mužů může vytvořit tábor, ale jenom jedna žena může vytvořit domov.",
    "Stává se, že jedna říše má tři pány.",
    "Štěstí nikdy nepřichází dvakrát, neštěstí nikdy nepřichází osaměle.",
    "Tím, co ti nahoře mají rádi, jsou ti dole posedlí.",
    "Tři dny děti netrestej – vylezou na střechu a sházejí tašky. Tři dny nečti a ústa zhrubnou. Tři dni nepiš a ruka zeslábne.",
    "V mělkém rybníce se nedaří velkým rybám.",
    "Velké duše mají vůli, ty malé pouze přání a touhy.",
    "Věci jsou takové, jaké jsou, ať je chápeš, nebo ne.",
    "Z hladiny moře měsíc neulovíš.",
    "Zacpat lidem ústa je těžší než ucpat protrženou hráz.",
    "Zpívat ve sboru a orat ve vodě umí každý.",
    "Žij si, jak chceš dlouho, nikdy se nedoučíš všeho.",
    "Wang je řešením všech problému.",
    "Veni, vidi, vici. - Wang",
    ":)",
    "Prostě si v píči.",
    'Nebuď si tak "skoro" jistej.',
    "Kdybys nebyl hlupákem, nestal by ses Torresem.",
    "Netrhejte motýlům křídla, vždyť oni pak pláčou.",
    "Nešlapte po kytkách, vždyť kytky tak krásně voní.",
    "Nezabíjejte lásku, vždyť láska je křehká jako ty kytky, a hlavně nezabíjejte lidi, vždyť lidi se milují. - Wang",
    "Lepší mít Albu v kapse než Wanga na střeše.",
    "Lepší býti retardem, než-li stát se Albovcem.",
    "Jdi na jedno.",
    "Hodně budeš někde.",
    "Je ti hodně.",
    "Nesnaž se, stejně ti nedá.",
    "Mmmmm, bolí to srdíčko, no.",
    "Kočku mam doma.",
    "Dáme výšlap na chiliad?",
    "Jak ti chutnala kočka?",
    "Myslíš si, že to nebyl pes?.",
    "Ták a teď víš jak chutná kočka.",
    "Neptej, se obsluhy z čeho je omáčka.",
    "Máš zlomené srdce? Smůla co?",
    "#Život",
    "Starý báby se musí střílet už za mlada.",
    "Kdo chce Albu bíti, hul si najde.",
    "Kdo rámen vaří, najde si brzo holku.",
    "Když se zapne první knoflík špatně, tak je celé zapínání špatné.",
    "Koho včera oběsili, k tomu se dnes modlí.",
    "Často bolí hlava toho, kdo ji ztratil. - Carlos Alba",
    "Muž vypadá zajímavě, žena v tomtéž případě je jen ošklivá.",
    "Ženy a kočky dělají, co chtějí, a muži a psi by se měli uklidnit a zvyknout si na to.",
    "Pes k člověku vzhlíží, kočka ho přehlíží a prase ho považuje za rovnocenného partnera.",
    "Průměrný pes je lepší osobnost než průměrný člověk.",
    "Pes je pravděpodobně nejlepší přítelem člověka proto, že nám neradí, nepůjčuje si od nás peníze a neobdarovává nás tchyněmi.",
    "Na rozdíl od žen psi milují jen jediného pána.",
    "Kdo chce hledat hůl, tak si ji vždycky najde. - Carlos Alba",
    "Zdar ty prase. - Fernando Torres",
    "Přátelé jsou jak brambory, když je sníš tak umřou.",
    "Nebudeš srát tam kde kadíš. - Ju Wang"
}
