Config = {}

Config.Price = 750.0

Config.Shops = {
    {['x'] = 355.55587768554, ['y'] = -594.89093017578, ['z'] = 42.28402709961, ['heading'] = 138.48446655274},
    {["x"] = -260.0598449707, ["y"] = 6327.9555664062, ["z"] = 31.427158355712, ["heading"] = 221.71229553222}
}

Config.medicJob = "ems"

Config.AllowedClothes = {
    ["sex"] = true,
    ["face"] = true,
    ["skin"] = true,
    ["hair_1"] = true,
    ["hair_2"] = true,
    ["hair_color_1"] = true,
    ["hair_color_2"] = true,
    ["tshirt_1"] = true,
    ["tshirt_2"] = true,
    ["torso_1"] = true,
    ["torso_2"] = true,
    ["decals_1"] = true,
    ["decals_2"] = true,
    ["arms"] = true,
    ["arms_2"] = true,
    ["pants_1"] = true,
    ["pants_2"] = true,
    ["shoes_1"] = true,
    ["shoes_2"] = true,
    ["eye_color"] = true,
    ["eyebrows_2"] = true,
    ["eyebrows_1"] = true,
    ["eyebrows_3"] = true,
    ["eyebrows_4"] = true,
    ["makeup_1"] = true,
    ["makeup_2"] = true,
    ["makeup_3"] = true,
    ["makeup_4"] = true,
    ["lipstick_1"] = true,
    ["lipstick_2"] = true,
    ["lipstick_3"] = true,
    ["lipstick_4"] = true,
    ["chest_1"] = true,
    ["chest_2"] = true,
    ["chest_3"] = true,
    ["bodyb_1"] = true,
    ["bodyb_2"] = true,
    ["age_1"] = true,
    ["age_2"] = true,
    ["blemishes_1"] = true,
    ["blemishes_2"] = true,
    ["blush_1"] = true,
    ["blush_2"] = true,
    ["blush_3"] = true,
    ["complexion_1"] = true,
    ["complexion_2"] = true,
    ["sun_1"] = true,
    ["sun_2"] = true,
    ["moles_1"] = true,
    ["moles_2"] = true,
    ["beard_1"] = true,
    ["beard_2"] = true,
    ["beard_3"] = true,
    ["beard_4"] = true,
    ["glasses_1"] = true,
    ["glasses_2"] = true,
    ["helmet_1"] = true,
    ["helmet_2"] = true,
    ["bags_1"] = true,
    ["bags_2"] = true
}
