Config.screenshotsInterval = 15

Config.whitelistedObjects = {
    [GetHashKey("prop_drink_redwine")] = true,
    [GetHashKey("prop_champ_flute")] = true,
    [GetHashKey("prop_el_guitar_03")] = true,
    [GetHashKey("p_amb_coffeecup_01")] = true,
    [GetHashKey("prop_cs_ciggy_01")] = true,
    [GetHashKey("prop_sponge_01")] = true,
    [GetHashKey("prop_cigar_02")] = true,
    [GetHashKey("prop_tourist_map_01")] = true,
    [GetHashKey("prop_npc_phone_02")] = true,
    [GetHashKey("p_amb_brolly_01")] = true,
    [GetHashKey("ba_prop_battle_champ_open")] = true,
    [GetHashKey("prop_novel_01")] = true,
    [GetHashKey("prop_cigar_01")] = true,
    [GetHashKey("prop_single_rose")] = true,
    [GetHashKey("prop_choc_ego")] = true,
    [GetHashKey("prop_cs_tablet")] = true,
    [GetHashKey("prop_cs_tablet")] = true,
    [GetHashKey("prop_acc_guitar_01")] = true,
    [GetHashKey("prop_police_id_board")] = true,
    [GetHashKey("prop_amb_ciggy_01")] = true,
    [GetHashKey("p_cs_joint_02")] = true,
    [GetHashKey("prop_ld_case_01")] = true,
    [GetHashKey("hei_heist_sh_bong_01")] = true,
    [GetHashKey("prop_mug_04")] = true,
    [GetHashKey("prop_drink_whisky")] = true,
    [GetHashKey("p_amb_clipboard_01")] = true,
    [GetHashKey("prop_cs_ciggy_01")] = true,
    [GetHashKey("prop_cs_ciggy_01")] = true,
    [GetHashKey("prop_beer_stzopen")] = true,
    [GetHashKey("prop_cardbordbox_02a")] = true,
    [GetHashKey("prop_el_guitar_01")] = true,
    [GetHashKey("v_ind_cfcup")] = true,
    [GetHashKey("prop_snow_flower_02")] = true,
    [GetHashKey("prop_pap_camera_01")] = true,
    [GetHashKey("prop_drink_champ")] = true,
    [GetHashKey("hei_prop_heist_box")] = true,
    [GetHashKey("p_michael_backpack_s")] = true,
    [GetHashKey("prop_acc_guitar_01")] = true,
    [GetHashKey("v_ilev_mr_rasberryclean")] = true,
    [GetHashKey("prop_npc_phone_02")] = true,
    [GetHashKey("prop_amb_beer_bottle")] = true,
    [GetHashKey("prop_sponge_01")] = true,
    [GetHashKey("prop_knife")] = true,
    [GetHashKey("prop_anim_cash_pile_01")] = true,
    [GetHashKey("prop_security_case_01")] = true,
    [GetHashKey("prop_beer_amopen")] = true,
    [GetHashKey("prop_sandwich_01")] = true,
    [GetHashKey("prop_mug_02")] = true,
    [GetHashKey("prop_amb_donut")] = true,
    [GetHashKey("prop_cs_burger_01")] = true,
    [GetHashKey("prop_beggers_sign_03")] = true,
    [GetHashKey("prop_ld_suitcase_01")] = true,
    [GetHashKey("prop_ecola_can")] = true,
    [GetHashKey("prop_notepad_01")] = true,
    [GetHashKey("prop_pencil_01")] = true,
    [GetHashKey("prop_plastic_cup_02")] = true,
    [GetHashKey("prop_energy_drink")] = true,
    [GetHashKey("prop_beer_logopen")] = true,
    [GetHashKey("prop_mug_01")] = true,
    [GetHashKey("prop_mug_03")] = true,
    [GetHashKey("ba_prop_battle_glowstick_01")] = true,
    [GetHashKey("ba_prop_battle_hobby_horse")] = true
}

Config.blacklistedVehicles = {
    [GetHashKey("vigilante")] = true,
    [GetHashKey("hydra")] = true,
    [GetHashKey("buzzard")] = true,
    [GetHashKey("deluxo")] = true,
    [GetHashKey("freight")] = true,
    [GetHashKey("avenger")] = true,
    [GetHashKey("akula")] = true,
    [GetHashKey("apc")] = true,
    [GetHashKey("barrage")] = true,
    [GetHashKey("caracara")] = true,
    [GetHashKey("cargobob")] = true,
    [GetHashKey("chernobog")] = true,
    [GetHashKey("hunter")] = true,
    [GetHashKey("insurgent")] = true,
    [GetHashKey("starling")] = true,
    [GetHashKey("lazer")] = true,
    [GetHashKey("bombushka")] = true,
    [GetHashKey("savage")] = true,
    [GetHashKey("rhino")] = true,
    [GetHashKey("khanjali")] = true,
    [GetHashKey("blimp")] = true
}

Config.FakeServerEvents = {
    "_chat:messageEntered",
    "esx_handcuffs:cuffing",
    "esx_policejob:handcuff",
    "esx_jailer:sendToJail",
    "esx_jail:sendToJail",
    "esx:giveInventoryItem",
    "esx_billing:sendBill",
    "esx_jailer:unjailTime",
    "esx-qalle-jail:jailPlayer",
    "esx_vehicletrunk:giveDirty",
    "esx_slotmachine:sv:2",
    "esx_moneywash:deposit",
    "esx_moneywash:withdraw",
    "Esx-MenuPessoal:Boss_recruterplayer",
    "esx:enterpolicecar",
    "esx:giveInventoryItem",
    "esx_blanchisseur:washMoney",
    "esx_blackmoney:washMoney",
    "esx_moneywash:withdraw",
    "esx_jailler:sendToJail",
    "esx-qalle-jail:jailPlayer",
    "esx_jail:sendToJail",
    "esx_jailer:sendToJailCatfrajerze",
    "esx_jail:sendToJail",
    "esx_ambulancejob:revive",
    "esx_ambulancejob:setDeathStatus",
    "esx_billing:sendBill",
    "esx_banksecurity:pay",
    "esx_blanchisseur:startWhitening",
    "esx_carthief:alertcops",
    "esx_carthief:pay",
    "esx_dmvschool:addLicense",
    "esx_dmvschool:pay",
    "esx:enterpolicecar",
    "esx_fueldelivery:pay",
    "esx:giveInventoryItem",
    "esx_garbagejob:pay",
    "esx_godirtyjob:pay",
    "esx_gopostaljob:pay",
    "esx_handcuffs:cuffing",
    "esx_jail:sendToJail",
    "esx_jail:unjailQuest",
    "esx_jailer:sendToJail",
    "esx_jailer:unjailTime",
    "esx_jobs:caution",
    "esx_mecanojob:onNPCJobCompleted",
    "esx_mechanicjob:startHarvest",
    "esx_mechanicjob:startCraft",
    "esx_pizza:pay",
    "esx_policejob:handcuff",
    "esx-qalle-jail:jailPlayer",
    "esx-qalle-jail:jailPlayerNew",
    "esx-qalle-hunting:reward",
    "esx-qalle-hunting:sell",
    "esx_ranger:pay",
    "esx:removeInventoryItem",
    "esx_truckerjob:pay",
    "esx_skin:responseSaveSkin",
    "esx_slotmachine:sv:2",
    "esx_society:getOnlinePlayers",
    "esx_society:setJob",
    "esx_vehicleshop:setVehicleOwned",
    "esx_skin:responseSaDFWMveSkin",
    "esx_dmvschool:addLiceDFWMnse",
    "esx_mechanicjob:starDFWMtCraft",
    "esx_drugs:startHarvestWDFWMeed",
    "esx_drugs:startTransfoDFWMrmWeed",
    "esx_drugs:startSellWeDFWMed",
    "esx_drugs:startHarvestDFWMCoke",
    "esx_drugs:startTransDFWMformCoke",
    "esx_drugs:startSellCDFWMoke",
    "esx_drugs:startHarDFWMvestMeth",
    "esx_drugs:startTDFWMransformMeth",
    "esx_drugs:startSellMDFWMeth",
    "esx_drugs:startHDFWMarvestOpium",
    "esx_drugs:startSellDFWMOpium",
    "esx_drugs:starDFWMtTransformOpium",
    "esx_blanchisDFWMseur:startWhitening",
    "esx_drugs:stopHarvDFWMestCoke",
    "esx_drugs:stopTranDFWMsformCoke",
    "esx_drugs:stopSellDFWMCoke",
    "esx_drugs:stopHarvesDFWMtMeth",
    "esx_drugs:stopTranDFWMsformMeth",
    "esx_drugs:stopSellMDFWMeth",
    "esx_drugs:stopHarDFWMvestWeed",
    "esx_drugs:stopTDFWMransformWeed",
    "esx_drugs:stopSellWDFWMeed",
    "esx_drugs:stopHarvestDFWMOpium",
    "esx_drugs:stopTransDFWMformOpium",
    "esx_drugs:stopSellOpiuDFWMm",
    "esx_society:openBosDFWMsMenu",
    "esx_jobs:caDFWMution",
    "esx_tankerjob:DFWMpay",
    "esx_vehicletrunk:givDFWMeDirty",
    "esx_vehicleshop:setVehicleOwnedPlayerId",
    "esx_blanchisseur:washMoney",
    "esx_moneywash:withdraw",
    "esx_blanchisseur:startWhitening",
    "esx_banksecurity:pay",
    "esx_drugs:pickedUpCDFWMannabis",
    "esx_drugs:processCDFWMannabis",
    "esx-qalle-hunting:DFWMreward",
    "esx-qalle-hunting:seDFWMll",
    "esx_mecanojob:onNPCJobCDFWMompleted",
    "esx_society:putVehicleDFWMInGarage",
    "esx:clientLog",
    "esx:triggerServerCallback",
    "esx:playerLoaded",
    "esx:createMissingPickups",
    "esx:updateLoadout",
    "esx:updateLastPosition",
    "esx:giveInventoryItem",
    "esx:removeInventoryItem",
    "esx:useItem",
    "esx:onPickup",
    "esx_status:set",
    "esx_skin:openRestrictedMenu",
    "esx_inventoryhud:openPlayerInventory",
    "esx_jobs:startWork",
    "esx_jobs:stopWork",
    "esx_fueldDFWMelivery:pay",
    "esx_carthDFWMief:pay",
    "esx_godiDFWMrtyjob:pay",
    "esx_pizza:pDFWMay",
    "esx_ranger:pDFWMay",
    "esx_garbageDFWMjob:pay",
    "esx_truckDFWMerjob:pay",
    "esx_jobs:caDFWMution",
    "esx_carthief:alertcoDFWMps",
    "esx:getShDFWMaredObjDFWMect",
    "esx_society:getOnlDFWMinePlayers",
    "esx_jailer:unjailTiDFWMme",
    "esx_ambulancejob:reDFWMvive",
    "esx_moneywash:depoDFWMsit",
    "esx_moneywash:witDFWMhdraw",
    "esx_handcuffs:cufDFWMfing",
    "esx_policejob:haDFWMndcuff",
    "esx-qalle-jail:jailPDFWMlayer",
    "esx_dmvschool:pDFWMay",
    "esx_biDFWMlling:sendBill",
    "esx_jDFWMailer:sendToJail",
    "esx_jaDFWMil:sendToJail",
    "esx_goDFWMpostaljob:pay",
    "esx_baDFWMnksecurity:pay",
    "esx_sloDFWMtmachine:sv:2",
    "esx:giDFWMveInventoryItem",
    "esx_vehicleshop:setVehicleOwnedDFWM",
    "esx_mafiajob:confiscateDFWMPlayerItem",
    "esx:getSharedObject",
    "NB:recruterplayer",
    "esx-qalle-jail:jailPlayer99",
    "ec49347f-474c-4b8e-a30d-9cc2476da5b3",
    "esx_society:openBossMenu",
    "esx_drugs:startHarvestWeed",
    "esx_drugs:startTransformWeed",
    "esx_drugs:startSellWeed",
    "esx_drugs:startHarvestCoke",
    "esx_drugs:startTransformCoke",
    "esx_drugs:startSellCoke",
    "esx_drugs:startHarvestMeth",
    "esx_drugs:startTransformMeth",
    "esx_drugs:startSellMeth",
    "esx_drugs:startHarvestOpium",
    "esx_drugs:startSellOpium",
    "esx_drugs:startTransformOpium",
    "esx_blanchisseur:startWhitening",
    "esx_drugs:stopHarvestCoke",
    "esx_drugs:stopSellCoke",
    "esx_drugs:stopTransformCoke",
    "esx_drugs:stopHarvestMeth",
    "esx_drugs:stopTransformMeth",
    "esx_drugs:stopSellMeth",
    "esx_weashopjob:addLicense",
    "esx_airlines:addLicense",
    "lscustoms:payGarage",
    "vrp_slotmachine:server:2",
    "ambulancier:selfRespawn",
    "esx-qalle-jail:openJailMenu"
}
